# AUTO GENERATED FILE - DO NOT EDIT

export fullcalendar

"""
    fullcalendar(;kwargs...)

A FullCalendar component.
DashFullCalendar – thin Dash wrapper around @fullcalendar/react.
ALL props (except the Dash house‑keeping ones) are forwarded verbatim.
No monkey‑patching of FullCalendar internals.
Keyword arguments:
- `id` (String; optional)
- `allDayClassNames` (Array | Dict | String; optional)
- `allDayContent` (a list of or a singular dash component, string or number; optional)
- `allDaySlot` (Bool; optional)
- `allDayText` (String; optional)
- `aspectRatio` (Real; optional)
- `businessHours` (Bool | Dict | Array; optional)
- `buttonIcons` (Dict; optional)
- `buttonText` (Dict; optional)
- `command` (Dict; optional): An object specifying a command to execute on the calendar API, such as {'type': 'next'} to navigate to the next period.
- `contentHeight` (Real | String; optional)
- `customButtons` (Dict; optional)
- `dateClick` (Bool | Real | String | Dict | Array; optional): The date string of the clicked date, for use in Dash callbacks.
- `datesSet` (Bool | Real | String | Dict | Array; optional): Object containing the current date range, for use in Dash callbacks.
- `dayCellClassNames` (Array | Dict | String; optional)
- `dayCellContent` (a list of or a singular dash component, string or number; optional)
- `dayHeaderClassNames` (Array | Dict | String; optional)
- `dayHeaderContent` (a list of or a singular dash component, string or number; optional)
- `dayHeaderFormat` (Dict | String; optional)
- `dayMaxEventRows` (Bool | Real; optional)
- `dayMaxEvents` (Bool | Real; optional)
- `dayMinWidth` (Real; optional)
- `dayPopoverFormat` (Dict | String; optional)
- `defaultAllDay` (Bool; optional)
- `dir` (String; optional)
- `displayEventEnd` (Bool; optional)
- `displayEventTime` (Bool; optional)
- `dragRevertDuration` (Real; optional)
- `dragScroll` (Bool; optional)
- `dropAccept` (String; optional)
- `droppable` (Bool; optional)
- `editable` (Bool; optional)
- `endParam` (String; optional)
- `eventAdd` (Bool | Real | String | Dict | Array; optional): Object containing information about the added event, for use in Dash callbacks.
- `eventBackgroundColor` (String; optional)
- `eventBorderColor` (String; optional)
- `eventChange` (Bool | Real | String | Dict | Array; optional): Object containing information about the changed event, for use in Dash callbacks.
- `eventClassNames` (Array | Dict | String; optional)
- `eventClick` (Bool | Real | String | Dict | Array; optional): Object containing information about the clicked event, for use in Dash callbacks.
- `eventColor` (String; optional)
- `eventConstraint` (Dict | String; optional)
- `eventContent` (a list of or a singular dash component, string or number; optional)
- `eventDisplay` (String; optional)
- `eventDrop` (Bool | Real | String | Dict | Array; optional): Object containing information about the dropped event, for use in Dash callbacks.
- `eventDurationEditable` (Bool; optional)
- `eventLongPressDelay` (Real; optional)
- `eventOrder` (Array | String; optional)
- `eventOrderStrict` (Bool; optional)
- `eventOverlap` (Bool; optional)
- `eventRemove` (Bool | Real | String | Dict | Array; optional): Object containing information about the removed event, for use in Dash callbacks.
- `eventResizableFromStart` (Bool; optional)
- `eventResize` (Bool | Real | String | Dict | Array; optional): Object containing information about the resized event, for use in Dash callbacks.
- `eventSources` (Array; optional)
- `eventStartEditable` (Bool; optional)
- `eventTextColor` (String; optional)
- `eventTimeFormat` (Dict | String; optional)
- `events` (Array | String; optional)
- `eventsSet` (Bool | Real | String | Dict | Array; optional): Array of current event objects in the calendar, for use in Dash callbacks.
- `expandRows` (Bool; optional)
- `firstDay` (Real; optional)
- `fixedWeekCount` (Bool; optional)
- `footerToolbar` (Dict | Bool; optional)
- `handleWindowResize` (Bool; optional)
- `headerToolbar` (Dict | Bool; optional)
- `height` (Real | String; optional)
- `hiddenDays` (Array; optional)
- `initialDate` (String; optional)
- `initialView` (String; optional)
- `lazyFetching` (Bool; optional)
- `listDayFormat` (Dict | String | Bool; optional)
- `listDaySideFormat` (Dict | String | Bool; optional)
- `locale` (String; optional)
- `locales` (Array; optional)
- `longPressDelay` (Real; optional)
- `moreLinkClassNames` (Array | Dict | String; optional)
- `moreLinkClick` (String; optional)
- `moreLinkContent` (a list of or a singular dash component, string or number; optional)
- `moreLinkText` (String; optional)
- `multiMonthMaxColumns` (Real; optional)
- `multiMonthMinWidth` (Real; optional)
- `multiMonthTitleFormat` (Dict | String; optional)
- `navLinkDayClick` (String; optional)
- `navLinkHint` (String; optional)
- `navLinkWeekClick` (String; optional)
- `navLinks` (Bool; optional)
- `nextDayThreshold` (String | Dict; optional)
- `noEventsClassNames` (Array | Dict | String; optional)
- `noEventsContent` (a list of or a singular dash component, string or number; optional)
- `now` (String; optional)
- `nowIndicator` (Bool; optional)
- `progressiveEventRendering` (Bool; optional)
- `rerenderDelay` (Real; optional)
- `scrollTime` (String | Dict; optional)
- `scrollTimeReset` (Bool; optional)
- `select` (Bool | Real | String | Dict | Array; optional): Object containing the selected range information, for use in Dash callbacks.
- `selectConstraint` (Dict | String; optional)
- `selectLongPressDelay` (Real; optional)
- `selectMinDistance` (Real; optional)
- `selectMirror` (Bool; optional)
- `selectOverlap` (Bool; optional)
- `selectable` (Bool; optional)
- `showNonCurrentDates` (Bool; optional)
- `slotDuration` (String | Dict; optional)
- `slotLabelClassNames` (Array | Dict | String; optional)
- `slotLabelContent` (a list of or a singular dash component, string or number; optional)
- `slotLabelFormat` (Array | Dict | String; optional)
- `slotLabelInterval` (String | Dict; optional)
- `slotLaneClassNames` (Array | Dict | String; optional)
- `slotLaneContent` (a list of or a singular dash component, string or number; optional)
- `slotMaxTime` (String | Dict; optional)
- `slotMinTime` (String | Dict; optional)
- `slotMinWidth` (Real; optional)
- `snapDuration` (String | Dict; optional)
- `startParam` (String; optional)
- `stickyFooterScrollbar` (Bool; optional)
- `stickyHeaderDates` (Bool; optional)
- `themeSystem` (String; optional)
- `timeZoneParam` (String; optional)
- `titleFormat` (Dict | String; optional)
- `unselect` (Bool | Real | String | Dict | Array; optional): Flag indicating unselection occurred, for use in Dash callbacks.
- `unselectAuto` (Bool; optional)
- `unselectCancel` (String; optional)
- `validRange` (Dict; optional)
- `viewClassNames` (Array | Dict | String; optional)
- `views` (Dict; optional)
- `weekNumberCalculation` (String; optional)
- `weekNumberFormat` (Dict | String; optional)
- `weekNumbers` (Bool; optional)
- `weekText` (String; optional)
- `weekTextLong` (String; optional)
- `weekends` (Bool; optional)
- `windowResizeDelay` (Real; optional)
"""
function fullcalendar(; kwargs...)
        available_props = Symbol[:id, :allDayClassNames, :allDayContent, :allDaySlot, :allDayText, :aspectRatio, :businessHours, :buttonIcons, :buttonText, :command, :contentHeight, :customButtons, :dateClick, :datesSet, :dayCellClassNames, :dayCellContent, :dayHeaderClassNames, :dayHeaderContent, :dayHeaderFormat, :dayMaxEventRows, :dayMaxEvents, :dayMinWidth, :dayPopoverFormat, :defaultAllDay, :dir, :displayEventEnd, :displayEventTime, :dragRevertDuration, :dragScroll, :dropAccept, :droppable, :editable, :endParam, :eventAdd, :eventBackgroundColor, :eventBorderColor, :eventChange, :eventClassNames, :eventClick, :eventColor, :eventConstraint, :eventContent, :eventDisplay, :eventDrop, :eventDurationEditable, :eventLongPressDelay, :eventOrder, :eventOrderStrict, :eventOverlap, :eventRemove, :eventResizableFromStart, :eventResize, :eventSources, :eventStartEditable, :eventTextColor, :eventTimeFormat, :events, :eventsSet, :expandRows, :firstDay, :fixedWeekCount, :footerToolbar, :handleWindowResize, :headerToolbar, :height, :hiddenDays, :initialDate, :initialView, :lazyFetching, :listDayFormat, :listDaySideFormat, :locale, :locales, :longPressDelay, :moreLinkClassNames, :moreLinkClick, :moreLinkContent, :moreLinkText, :multiMonthMaxColumns, :multiMonthMinWidth, :multiMonthTitleFormat, :navLinkDayClick, :navLinkHint, :navLinkWeekClick, :navLinks, :nextDayThreshold, :noEventsClassNames, :noEventsContent, :now, :nowIndicator, :progressiveEventRendering, :rerenderDelay, :scrollTime, :scrollTimeReset, :select, :selectConstraint, :selectLongPressDelay, :selectMinDistance, :selectMirror, :selectOverlap, :selectable, :showNonCurrentDates, :slotDuration, :slotLabelClassNames, :slotLabelContent, :slotLabelFormat, :slotLabelInterval, :slotLaneClassNames, :slotLaneContent, :slotMaxTime, :slotMinTime, :slotMinWidth, :snapDuration, :startParam, :stickyFooterScrollbar, :stickyHeaderDates, :themeSystem, :timeZoneParam, :titleFormat, :unselect, :unselectAuto, :unselectCancel, :validRange, :viewClassNames, :views, :weekNumberCalculation, :weekNumberFormat, :weekNumbers, :weekText, :weekTextLong, :weekends, :windowResizeDelay]
        wild_props = Symbol[]
        return Component("fullcalendar", "FullCalendar", "dash_fullcalendar", available_props, wild_props; kwargs...)
end

